config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "lists#index"

  get 'lists/new', to: 'lists#new', as: :new_list
  post 'lists', to: 'lists#create'

  get 'list/:id', to: 'lists#show', as: :list

  get 'list/:id/bookmarks/new', to: 'bookmarks#new', as: :new_bookmark
  post 'list/:id/bookmarks', to: 'bookmarks#create'

  delete 'bookmarks/:id', to: 'bookmarks#destroy', as: :bookmarks

  get 'list/:id/bookmarks', to: 'bookmarks#show', as: :list_bookmarks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  # validates :comment, presence: true
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, :overview, presence: true
  validates :rating, comparison: { greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }, unless: -> { rating.nil? }
  validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @list = params[:list]
    @bookmarks = Bookmark.where(list: params[:list])
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  def index
    @bookmarks = Bookmark.all
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/index.html.erb
<h1>Bookmarks#index</h1>
<p>Find me in app/views/bookmarks/index.html.erb</p>

app/views/bookmarks/new.html.erb
<h1>New bookmark</h1>
<div class="container">
  <%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <div class="container py-3">
    <%= yield %>
  </div>
  </body>
</html>

app/views/lists/index.html.erb
<h1>Lists</h1>
<ul class="list-group">
  <% @lists.each do |list| %>
  <li class="list-group-item">
    <%= link_to list.name, list_path(list) %>
  </li>
  <% end %>
</ul>
<div class="container py-3">
  <%= link_to "Create new List",  new_list_path %>
</div>

app/views/lists/new.html.erb
<h1>New list</h1>
<div class="container">
  <%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>
</div>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
<ul class="list-group">
  <% @list.bookmarks.each do |item| %>
    <li class="list-group-item"><%= item.movie.title %></li>
    <li class="list-group-item">
      <%= item.comment %>
      <%= link_to "Delete bookmark", bookmarks_path(item), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
    </li>
  <% end %>
</ul>

<div class="container">
  <%= link_to 'Add new movie to this watchlist', new_bookmark_path %>
</div>